### ISSUE TITLE
[cmder] Clink completion doesn't work for powershell

### ISSUE THREAD

**Issue by chawyehsu** [Elvyria/scoop-clink-completion#1]
![main](https://user-images.githubusercontent.com/5764917/46911831-a4679d80-cf99-11e8-8378-1368a937e650.gif)

Still shows files in current directory. Cmder + PowerShell 5.1

**Comment by Elvyria** [comment]
Is it exclusive to powershell task or it doesn't work for cmd aswell?
(`-new_console:d:C:\Users\UserName cmd /k ""%ConEmuDir%\..\init.bat" "`)

**Comment by chawyehsu** [comment]
It works after launching cmd using the command you provided. Is it possible to support powershell?

**Comment by Elvyria** [comment]
[Clink](https://github.com/mridgers/clink) documentation tells that it has some 'basic' (whatever that suppose to mean) support for powershell, but i could not make it work. You can try to use ps script from [this](https://github.com/liuzijing97/scoop-auto-completion) repository, but i can't confirm that it works. You can also try to make clink work with powershell or maybe there's some random clink fork that can do it. I doubt that i can make something with it, but i will definitely dig deeper into this problem later.
(Let me know if you could make clink + powershell work)
Related Issues: mridgers/clink#74, mridgers/clink#256

**Comment by denyncrawford** [comment]
@Elvyria did you find any solution?

**Comment by Elvyria** [comment]
No. Current actual [fork](https://github.com/chrisant996/clink/) of clink contains changes from [commit](https://github.com/chrisant996/clink/commit/39afd58d7cee03eb3e9fed7d17eeb74de9fada81) that completely strips any powershell support.
Sorry, can't be much help here, since i'm not using powershell myself.
